name: movato
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  youtube_player_flutter: ^8.1.2


  flutter_svg: ^2.0.9
  google_sign_in: ^6.1.5
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  package_info_plus: ^9.0.0

  google_fonts: ^6.2.1
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  flutter_riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
